-- =================================================================================
-- 1. LIMPIEZA
-- =================================================================================
DROP TABLE IF EXISTS auditoria_ordenes;
DROP TABLE IF EXISTS work_orders;
DROP TABLE IF EXISTS tecnicos;
DROP TABLE IF EXISTS usuarios;

-- =================================================================================
-- 2. TABLAS PRINCIPALES
-- =================================================================================
CREATE TABLE usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_usuario VARCHAR(255) NOT NULL,
    password_usuario VARCHAR(255) NOT NULL,
    name_usuario VARCHAR(255) NOT NULL,
    role_usuario VARCHAR(255) NOT NULL
);
ALTER TABLE usuarios ADD CONSTRAINT uk_usuarios_email UNIQUE (email_usuario);

CREATE TABLE tecnicos (
    id_tecnico BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_tecnico VARCHAR(255) NOT NULL,
    zone_tecnico VARCHAR(255) NOT NULL,
    workload_tecnico VARCHAR(255) NOT NULL,
    speciality_tecnico VARCHAR(255) NOT NULL
);
ALTER TABLE tecnicos ADD CONSTRAINT uk_tecnicos_name UNIQUE (name_tecnico);

CREATE TABLE work_orders (
    id_order BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_cliente VARCHAR(255) NOT NULL,
    phone_cliente VARCHAR(255) NOT NULL,
    tipo_servicio VARCHAR(255) NOT NULL,
    prioridad VARCHAR(255) NOT NULL,
    estado VARCHAR(255) NOT NULL,
    descripcion VARCHAR(1000),
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_tecnico_asignado BIGINT,
    CONSTRAINT fk_work_orders_tecnico FOREIGN KEY (id_tecnico_asignado) REFERENCES tecnicos(id_tecnico)
);

-- Tabla para el Requisito de Auditoría (Sprint 3)
CREATE TABLE auditoria_ordenes (
    id_audit BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden BIGINT,
    estado_anterior VARCHAR(255),
    estado_nuevo VARCHAR(255),
    fecha_cambio TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =================================================================================
-- 3. TRIGGER (Requiere la clase Java AuditTrigger)
-- =================================================================================
CREATE TRIGGER IF NOT EXISTS trg_audit_orders
AFTER UPDATE ON work_orders
FOR EACH ROW
CALL "com.telconovaP7F22025.demo.util.AuditTrigger";

-- =================================================================================
-- 4. DATOS DE PRUEBA (POBLADO)
-- =================================================================================

-- Usuarios (Password 'secret' en BCrypt)
INSERT INTO usuarios (email_usuario, password_usuario, name_usuario, role_usuario) VALUES 
('admin@telconova.com', '$2a$10$76jDh/40RDpBWeB/YFwSW.V/RPSBnS8AB3A7R271dWHeZyWvKOSri', 'Admin Principal', 'ADMIN'),
('tecnico@telconova.com', '$2a$10$76jDh/40RDpBWeB/YFwSW.V/RPSBnS8AB3A7R271dWHeZyWvKOSri', 'Tecnico Campo', 'USER');

-- Técnicos
INSERT INTO tecnicos (name_tecnico, zone_tecnico, workload_tecnico, speciality_tecnico) VALUES 
('Carlos Diaz', 'Norte', '2', 'Fibra Optica'),
('Ana Maria Polo', 'Sur', '5', 'Redes HFC'),
('Pedro Picapiedra', 'Occidente', '1', 'Infraestructura');

-- Órdenes de Trabajo
INSERT INTO work_orders (name_cliente, phone_cliente, tipo_servicio, prioridad, estado, descripcion, id_tecnico_asignado) VALUES 
('Empresa ABC', '3001234567', 'Reparación Internet', 'ALTA', 'PENDIENTE', 'Sin conexión total', NULL),
('Juan Valdéz', '3109876543', 'Instalación TV', 'MEDIA', 'ASIGNADA', 'Solicita deco adicional', 1),
('Hotel Plaza', '3201112233', 'Falla Masiva', 'URGENTE', 'EN_PROGRESO', 'Piso 4 sin señal', 2),
('Restaurante Cielo', '3005556677', 'Cambio Router', 'BAJA', 'FINALIZADA', 'Equipo obsoleto cambiado', 1);